### ISSUE TITLE
mac m1 build problem

### ISSUE THREAD

**Issue by huahuayu** [lwthiker/curl-impersonate#192] opened 2023-09-26 11:30 UTC
Hi, I build from Mac m1, follow the [build doc](https://github.com/lwthiker/curl-impersonate/blob/main/INSTALL.md#macos) and the build was successful, but when use curl_chrome or curl_firefox get an error like this:

```
./curl_ff100: line 10: ./curl-impersonate-ff: No such file or directory
```

```
./curl_chrome116: line 10: ./curl-impersonate-chrome: No such file or directory
```

commit 845db62e79853081f5b8396b9a8ce34500d80100

```
$ tree -L 1
.
├── Dockerfile
├── Dockerfile.alpine
├── curl_chrome100
├── curl_chrome101
├── curl_chrome104
├── curl_chrome107
├── curl_chrome110
├── curl_chrome116
├── curl_chrome99
├── curl_chrome99_android
├── curl_edge101
├── curl_edge99
├── curl_safari15_3
├── curl_safari15_5
└── patches
```

```
$ tree -L 1
.
├── Dockerfile
├── Dockerfile.alpine
├── curl_ff100
├── curl_ff102
├── curl_ff109
├── curl_ff117
├── curl_ff91esr
├── curl_ff95
├── curl_ff98
└── patches
```

If only there's precompiled binaray.

**Comment by lwthiker** [comment] 2024-03-02 14:06
The problem is that the compiled binaries (e.g. `curl-impersonate-chrome`) are not in your PATH. You need to run `gmake chrome-install` in order to install them to a system location. This will also install the scripts to the same directory.

Closing for now, please reopen if it's not resolved.

**Closed by lwthiker** 2024-03-02 14:06 UTC
