### ISSUE TITLE
415 Unsupported Media Type

### ISSUE THREAD

**Issue by Prodian0013** [lwthiker/curl-impersonate#18] opened 2022-03-03 16:40 UTC
Seems to be an encoding issue when adding Content-Type header with a space.

Doesnt work:
` -H 'Content-Type: application/json' `

Returns:
`[{"status":"FAILURE","message":"HTTP 415 Unsupported Media Type","code":"{unsupported.media.type}","requestedUrl":"/search/template"}]curl: (6) Could not resolve host: application`

Works:
` -H 'Content-Type:application/json' `

**Comment by lwthiker** [comment] 2022-03-04 15:17
@Prodian0013 Thank you for opening this, it was a stupid error in the wrapper scripts. Not even related to content encoding. Can you test #19? It's supposed to solve it.

**Comment by lwthiker** [comment] 2022-03-05 11:17
@Prodian0013 I'm merging #19 and closing this, I'm pretty certain the problem is solved. If the issue persists please re-open.

**Closed by lwthiker** 2022-03-05 11:17 UTC
